name: Scheduled Reddit Newsletter Email

on:
  schedule:
    - cron: "0 7 * * *"  # Runs at 8 AM CET (7 AM UTC)
    - cron: "0 20 * * *" # Runs at 9 PM CET (8 PM UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full repo is checked out

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Verify requirements file exists
        run: ls -l requirements.txt || echo "requirements.txt NOT FOUND"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "Skipping dependency installation: requirements.txt not found"; fi

      - name: Create .env file
        run: |
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
          echo "REDDIT_USERNAME=${{ secrets.REDDIT_USERNAME }}" >> .env
          echo "REDDIT_PASSWORD=${{ secrets.REDDIT_PASSWORD }}" >> .env
          echo "USER_AGENT=${{ secrets.USER_AGENT }}" >> .env

      - name: Run Reddit newsletter script
        run: python reddit_newsletter.py
