name: Scheduled Reddit Newsletter Email

on:
  schedule:
    - cron: "0 7 * * *"  # Runs at 8 AM CET (7 AM UTC)
    - cron: "0 20 * * *"  # Runs at 9 PM CET (8 PM UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  send_email:
    runs-on: windows-latest  # ⚠️ Runs on Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Parse API_KEYS and create .env file
        shell: pwsh  # Use PowerShell for JSON parsing in Windows
        run: |
          $api_keys = ConvertFrom-Json '${{ secrets.API_KEYS }}'
          Set-Content -Path .env -Value "CLIENT_ID=$($api_keys.CLIENT_ID)"
          Add-Content -Path .env -Value "CLIENT_SECRET=$($api_keys.CLIENT_SECRET)"
          Add-Content -Path .env -Value "REDDIT_USERNAME=$($api_keys.REDDIT_USERNAME)"
          Add-Content -Path .env -Value "REDDIT_PASSWORD=$($api_keys.REDDIT_PASSWORD)"
          Add-Content -Path .env -Value "USER_AGENT=$($api_keys.USER_AGENT)"
          Add-Content -Path .env -Value "EMAIL_SENDER=$($api_keys.EMAIL_SENDER)"
          Add-Content -Path .env -Value "EMAIL_PASSWORD=$($api_keys.EMAIL_PASSWORD)"
          Add-Content -Path .env -Value "EMAIL_RECEIVER=$($api_keys.EMAIL_RECEIVER)"

      - name: Run Reddit newsletter script
        run: python reddit_newsletter.py
